#!/bin/sh

. /etc/os-release
. /lib/functions/uci-defaults.sh

[ $(uname -m) = "x86_64" ] && alias board_name="echo x86_64"
[ "$OPENWRT_BOARD" = "armsr/armv8" ] && alias board_name="echo armsr,armv8"

# OTA
if [ "$VERSION_TYPE" = "minimal" ]; then
    OTA_URL="https://github.71557.dpdns.org/https://raw.githubusercontent.com/s71557/iStoreOS-Actions/refs/heads/api/fw.json"
else
    OTA_URL="https://github.71557.dpdns.org/https://raw.githubusercontent.com/s71557/iStoreOS-Actions/refs/heads/api/fw.json"
fi

devices_setup()
{
    case "$(board_name)" in
    armsr,armv8)
        [ $(uname -r | awk -F. '{print $1}') = 6 ] && {
            [ ! -d "/usr/share/openwrt_core" ] && {
                openwrt_core="openwrt_core/armsr-armv8"
                sed -i '/openwrt_core/d' /etc/opkg/distfeeds.conf
                sed -i "\$a\src/gz openwrt_core https://github.71557.dpdns.org/https://raw.githubusercontent.com/s71557/${openwrt_core}/$(grep Version /usr/lib/opkg/info/kernel.control | awk '{print $2}')" /etc/opkg/distfeeds.conf
            }
            uci set ota.config.api_url="$OTA_URL"
            uci commit ota
        }
        ;;
    friendlyarm,nanopi-r4s|\
    friendlyarm,nanopi-r5c|\
    friendlyarm,nanopi-r5s)
        uci set irqbalance.irqbalance.enabled='0'
        uci commit irqbalance
        service irqbalance stop
        [ ! -d "/usr/share/openwrt_core" ] && {
            openwrt_core="openwrt_core/aarch64_generic"
            sed -i '/openwrt_core/d' /etc/opkg/distfeeds.conf
            sed -i "\$a\src/gz openwrt_core https://github.71557.dpdns.org/https://raw.githubusercontent.com/s71557/${openwrt_core}/$(grep Version /usr/lib/opkg/info/kernel.control | awk '{print $2}')" /etc/opkg/distfeeds.conf
        }
        uci set ota.config.api_url="$OTA_URL"
        uci commit ota
        ;;
    netgear,r8500)
        [ ! -d "/usr/share/openwrt_core" ] && {
            openwrt_core="openwrt_core/arm_cortex-a9"
            sed -i '/openwrt_core/d' /etc/opkg/distfeeds.conf
            sed -i "\$a\src/gz openwrt_core https://github.71557.dpdns.org/https://raw.githubusercontent.com/s71557/${openwrt_core}/$(grep Version /usr/lib/opkg/info/kernel.control | awk '{print $2}')" /etc/opkg/distfeeds.conf
        }
        uci set ota.config.api_url="$OTA_URL"
        uci commit ota
        ;;
    x86_64)
        [ $(uname -r | awk -F. '{print $1}') = 6 ] && {
            [ -f /sys/kernel/btf/vmlinux ] && [ ! -d "/usr/share/openwrt_core" ] && {
                sed -i '/openwrt_core/d' /etc/opkg/distfeeds.conf
                sed -i "\$a\src/gz openwrt_core https://core.cooluc.com/x86_64/$(grep Version /usr/lib/opkg/info/kernel.control | awk '{print $2}')" /etc/opkg/distfeeds.conf
            }
        }
        uci set ota.config.api_url="$OTA_URL"
        uci commit ota
        ;;
    esac
}

# 调用 devices_setup 函数
devices_setup

exit 0
