#!/bin/sh

. /etc/os-release
. /lib/functions/uci-defaults.sh

[ $(uname -m) = "x86_64" ] && alias board_name="echo x86_64"
[ "$OPENWRT_BOARD" = "armsr/armv8" ] && alias board_name="echo armsr,armv8"

# OTA
if [ "$VERSION_TYPE" = "minimal" ]; then
    OTA_URL="https://raw.githubusercontent.com/Jaykwok2999/istoreos-actions/refs/heads/api/fw.json"
else
    OTA_URL="https://raw.githubusercontent.com/Jaykwok2999/istoreos-actions/refs/heads/api/fw.json"
fi

devices_setup()
{
    case "$(board_name)" in
    armsr,armv8)
        [ $(uname -r | awk -F. '{print $1}') = 6 ] && {
            [ ! -d "/usr/share/openwrt_core" ] && {
                openwrt_core="openwrt_core/armsr-armv8"
                sed -i '/openwrt_core/d' /etc/opkg/distfeeds.conf
                sed -i "\$a\src/gz openwrt_core https://raw.githubusercontent.com/Jaykwok2999/${openwrt_core}/$(grep Version /usr/lib/opkg/info/kernel.control | awk '{print $2}')" /etc/opkg/distfeeds.conf
            }
            uci set ota.config.api_url="$OTA_URL"
            uci commit ota

uci -q batch <<-EOF
	set system.@system[0].hostname='iStoreOS'
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'

	delete system.ntp.server
	add_list system.ntp.server='ntp1.aliyun.com'
	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='time.apple.com'
EOF
uci commit system

# 设置默认主题为argon
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci

# opkg mirror
if [ $(grep -c SNAPSHOT /etc/opkg/distfeeds.conf) -eq '0' ]; then
    sed -i 's,downloads.openwrt.org,mirrors.aliyun.com/openwrt,g' /etc/opkg/distfeeds.conf
else
    sed -i 's,downloads.openwrt.org,mirror.sjtu.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf
fi

# zram
mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')
zram_size=$(echo | awk "{print int($mem_total*0.25/1024)}")
uci set system.@system[0].zram_size_mb="$zram_size"
uci set system.@system[0].zram_comp_algo='zstd'
uci commit system

# 配置流量卸载
uci set firewall.@defaults[0].flow_offloading=1
uci commit firewall
/etc/init.d/firewall restart

# 默认wan口防火墙打开
uci set firewall.@zone[1].input='ACCEPT'
uci commit firewall

# diagnostics
uci set luci.diag.dns='www.baidu.com'
uci set luci.diag.ping='www.baidu.com'
uci set luci.diag.route='www.baidu.com'
uci commit luci

# 设置主机名映射，解决安卓原生TV首次连不上网的问题
uci add dhcp domain
uci set "dhcp.@domain[-1].name=time.android.com"
uci set "dhcp.@domain[-1].ip=203.107.6.88"
uci commit dhcp

# 设置所有网口可访问网页终端
uci delete ttyd.@ttyd[0].interface

# 设置所有网口可连接 SSH
uci set dropbear.@dropbear[0].Interface=''
uci commit

if [ "$( opkg list-installed 2>/dev/null| grep -c "^dnsmasq")" -ne '0' ];then
  uci set dhcp.@dnsmasq[0].cachesize='0'
  uci commit dhcp
  /etc/init.d/dnsmasq restart
fi



# adguardhome
if [ "$( opkg list-installed 2>/dev/null| grep -c "^luci-app-adguardhome")" -ne '0' ];then
uci batch << EOI
set AdGuardHome.AdGuardHome.enabled='1'
set AdGuardHome.AdGuardHome.httpport='3000'
set AdGuardHome.AdGuardHome.binpath='/usr/bin/AdGuardHome/AdGuardHome'
set AdGuardHome.AdGuardHome.waitonboot='1'
set AdGuardHome.AdGuardHome.redirect='dnsmasq-upstream'
set AdGuardHome.AdGuardHome.ucitracktest='1'
set AdGuardHome.AdGuardHome.old_redirect='dnsmasq-upstream'
set AdGuardHome.AdGuardHome.old_port='1745'
set AdGuardHome.AdGuardHome.old_enabled='1'
EOI
  uci commit AdGuardHome
  /etc/init.d/AdGuardHome restart


exit 0
